clear all; clc;
Fs = 200e3; % Частота дискретизации, выборок в с
% Инициализации параметров синусоиды
TxSine.Frequency       = 100; 
TxSine.Amplitude       = 1;
TxSine.ComplexOutput   = true;
TxSine.SampleRate      = Fs; 
TxSine.SamplesPerFrame = 2048;
TxSine.OutputDataType  = 'double';
% Инициализация системного объекта dsp.SineWave
hSineSource = dsp.SineWave (...
    'Frequency',       TxSine.Frequency, ...
    'Amplitude',       TxSine.Amplitude,...
    'ComplexOutput',   TxSine.ComplexOutput, ...
    'SampleRate',      TxSine.SampleRate, ...
    'SamplesPerFrame', TxSine.SamplesPerFrame, ...
    'OutputDataType',  TxSine.OutputDataType);
% Обнаружение подключенного устройства USRP
connectedRadios = findsdru;
% Инициализация типа устройства USRP
txradio.Platform = connectedRadios.Platform;
% Инициализация серийного номера устройства USRP
txradio.SerialNum = connectedRadios.SerialNum;
% Инициализация параметров передачи устройства USRP
txradio.MasterClockRate = 20e6;  % тактовая частота, Гц
txradio.CenterFrequency = 450e6; % центральная частота
txradio.Gain            = 40;    % усиление, дБ 
% Коэффициент интерполяции
txradio.InterpolationFactor = txradio.MasterClockRate/Fs;
% Инициализация системного объекта comm.SDRuTransmitter
txradio = comm.SDRuTransmitter( ...
      'Platform',            txradio.Platform, ...
      'SerialNum',           txradio.SerialNum, ...
      'MasterClockRate',     txradio.MasterClockRate, ...
      'CenterFrequency',     txradio.CenterFrequency -...
                                    TxSine.Frequency,...
      'Gain',                txradio.Gain,...
      'InterpolationFactor', txradio.InterpolationFactor);
% Инициализация системного объекта dsp.SpectrumAnalyzer 
hSpectrumAnalyzer = dsp.SpectrumAnalyzer(...
    'Name',             'Спектр переданной синусоиды',...
    'Title',            'Спектр переданной синусоиды',...
    'FrequencySpan',    'Full', ...
    'SampleRate',       Fs, ...
    'SpectralAverages', 50, ...
    'FrequencySpan',    'Start and stop frequencies', ...
    'StartFrequency',   -10e3, ...
    'StopFrequency',    10e3);
% Передача синусоиды для заданного числа кадров
TotalFrames = 20000;
for iFrame = 1: TotalFrames
    sinewave =  hSineSource();  % формирование синусоиды
    txradio(sinewave);          % передача синусоиды в радиоэфир
    hSpectrumAnalyzer(sinewave);% спектр синусоиды
end
% Освобождение системных объектов
release(txradio); release(hSineSource); 
release(hSpectrumAnalyzer); 