clear all; clc;
Fs = 200e3; % Частота дискретизации, выборок в с
TotalFrames = 1000000; % число кадров для приема
% Обнаружение подключенного устройства USRP
connectedRadios = findsdru;
% Инициализация типа устройства USRP
rxradio.Platform = connectedRadios.Platform;
% Инициализация серийного номера устройства USRP
rxradio.SerialNum = connectedRadios.SerialNum;
% Инициализация параметров приема устройства USRP
rxradio.MasterClockRate  = 20e6;  % тактовая частота, Гц
rxradio.CenterFrequency  = 450e6; % центральная частота
rxradio.Gain             = 40;    % усиление, дБ 
rxradio.DecimationFactor = rxradio.MasterClockRate/Fs;
rxradio.SamplesPerFrame  = 4096;  % выборок в кадре
rxradio.OutputDataType   = 'double'; 
TotalFrames     = 20000;  % число кадров
% Инициализация системного объекта comm.SDRuReceiver
rxradio = comm.SDRuReceiver(...
    'Platform',         rxradio.Platform, ...
    'SerialNum',        rxradio.SerialNum, ...
    'MasterClockRate',  rxradio.MasterClockRate, ...
    'CenterFrequency',  rxradio.CenterFrequency,...
    'Gain',             rxradio.Gain, ...
    'DecimationFactor', rxradio.DecimationFactor,...
    'SamplesPerFrame',  rxradio.SamplesPerFrame,...
    'OutputDataType',   rxradio.OutputDataType);  
% Инициализация системного объекта dsp.SineWave
hSpectrumAnalyzer = dsp.SpectrumAnalyzer(...
    'Name',             'Спектр принятой синусоиды',...
    'Title',            'Спектр принятой синусоиды',...
    'SpectrumType',     'Power density',...
    'FrequencySpan',    'Full', ...
    'SampleRate',       Fs, ...
    'SpectralAverages', 50, ...
    'FrequencySpan',    'Start and stop frequencies',...
    'StartFrequency',   -10e3, ...
    'StopFrequency',    10e3);
% Прием синусоиды для заданного числа кадров
for iFrame = 1 : TotalFrames
    [rxsig, len] = rxradio();
    if len > 0
        hSpectrumAnalyzer(rxsig);
        offset_f = freqoffset(rxsig,Fs);
        disp(['сдвиг = ',num2str(offset_f),' Гц']);
    end
end 
% Освобождение системных объектов
release(rxradio); release(hSpectrumAnalyzer); 